name: Fetch Data and Update

permissions:
  contents: write  # Needed for pushing changes

on:
  push:
    branches: [ master ]   # Change this if your default branch is 'master'
  repository_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Fetch Data
    runs-on: ubuntu-latest

    env:
      URL2: ${{ secrets.URL2 }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python index.py

      - name: Commit and Push Report
        run: |
          # Configure git
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.EMAIL }}"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          # Check current branch
          git branch
          git checkout master  # Ensure we are on master branch (if your default branch is master)

          # Add, commit, push
          git add -A
          git commit -m "Automated data update" || echo "No changes to commit"
          git push --force origin master || echo "No changes to push"
