on:
  push:
    branches: [master]  # Trigger workflow on push to main branch
  repository_dispatch:  # Trigger workflow on repository dispatch events
  schedule:
    - cron: "*/5 * * * *"  # Schedule workflow to run every 5 minutes
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    name: Fetch Data  # Job name
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: '3.9'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Set environment variables
        run: echo "URL2=${{ secrets.URL2 }}" >> $GITHUB_ENV  # Set URL2 from secret

      - name: Run Python script
        run: python index.py  # Run your Python script (replace 'index.py' if needed)

      - name: Commit and Push Report
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"  # Configure user name from secret
          git config --global user.email "${{ secrets.EMAIL }}"  # Configure user email from secret
          git remote set-url origin https://github.com/${{ github.repository }}  # Set remote URL without token

          git add -A  # Add all changes
          git commit -m "Automated data update" || echo "No changes to commit"  # Commit changes if there are any
          git push --force --set-upstream origin main || echo "No changes to push"  # Push changes or log if nothing to push
